Models/ApplicationContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class ApplicationContext:DbContext
    {
        public ApplicationContext(DbContextOptions<ApplicationContext>options) : base(options) { }
        public DbSet<Country> Countries { get; set; }
        public DbSet<State> States { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<DropState> DropStates { get; set; }
        public DbSet<DropCity> DropCities { get; set; }
        public DbSet<Employee> Employees { get; set; }

    }
}

Models/City.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class City
    {
        [Key]
        public int MyProperty { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public State State { get; set; }
    }

}

Models/Country.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class Country
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
    }

}

Models/DropCity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class DropCity
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public State State { get; set; }
    }
}

Models/DropState.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class DropState
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class Employee
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }

        [Required(ErrorMessage = "State is required.")]
        public string State { get; set; }
        public string City { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace CascadingDropdown.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/State.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Models
{
    public class State
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Country Country { get; set; }
    }

}

Controllers/CascadeController.cs
using CascadingDropdown.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Controllers
{
    public class CascadeController : Controller
    {
        private readonly ApplicationContext context;

        public CascadeController(ApplicationContext context)
        {
            this.context = context;
        }   

        public IActionResult Index()
        {
            ViewBag.countries = context.Countries.ToList();
            return View();
        }
        public JsonResult getStateById(int id)
        {
            List<State> list =new List<State>();
            list = context.States.Where(e => e.Country.Id == id).ToList();
            list.Insert(0, new State { Id = 0, Name = "Please Select State" });
            return Json(new SelectList(list,"Id","Name"));
        }
    }
}

Controllers/DropController.cs
using CascadingDropdown.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Controllers
{
    public class DropController : Controller
    {
        private readonly ApplicationContext context;

        public DropController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var emp = context.Employees.ToList();
            return View(emp);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            context.Employees.Add(employee);
            context.SaveChanges();
            return View("Index");
        }
        public IActionResult GetState()
        {
            var State = context.DropStates.ToList();
            return Json(State);
        }
        public IActionResult GetCity(int id)
        {
            var City = context.DropCities.Where(e => e.State.Id == id).ToList();
            return Json(City);
        }

    }
}

Controllers/DropdownController.cs
using CascadingDropdown.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Controllers
{
    public class DropdownController : Controller
    {
        private readonly ApplicationContext context;

        public DropdownController(ApplicationContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
           
            return View();
        }


        public IActionResult GetCountries()
        {
            var countries = this.context.Countries.ToList();
            return Json(countries);
        }


        public IActionResult GetStates(int id)
        {
            var states = this.context.States.Where(e => e.Country.Id == id).ToList();
            return Json(states);
        }

        public IActionResult GetCities(int id)
        {
            var cities = this.context.Cities.Where(e => e.State.Id == id).ToList();
            return Json(cities);
        }
        public IActionResult Validation()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Validation(Employee employee)
        {
            return View();
        }

    }
}

Controllers/HomeController.cs
using CascadingDropdown.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CascadingDropdown.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Cascade/Index.cshtml
@model CascadingDropdown.Models.Country
@{
    ViewData["Title"] = "Index";
}

<label asp-for="Name"></label>
<select id="CountryId" name="CountryList" asp-for="Id" asp-items='@(new SelectList(ViewBag.countries,"Id","Name"))'>
    <option >--Select Country--</option>

</select>

<select id="StateId" name="StateList" asp-for="Id" asp-items='@(new SelectList(string.Empty,"Id","Name"))'>
    
   
</select>
<button onclick="Hello()">Hello</button>
<script>
    $(function () {
        $("#CountryId").change(function () {
            var url = '@Url.Content("~/")' + "Cascade/getStateById";
            var ddlsource = "#CountryId";
            $.getJSON(url, { id:(ddlsource).val() }, function (data) {
            var items = '';
            $("#StateId").empty();
                $.each(data, function (i, row) {
                    items += "<option value='" + row.value + "'>" + row.text + "</option>";
                });
                $(StateId).html(items);
        });
       
        });
    });
</script>

Views/Drop/Create.cshtml
@model CascadingDropdown.Models.Employee
@{
    ViewData["Title"] = "Create";
}

<div class="container">
    <div class="row">
        <div class="col-6 offset-3">
            <h1 class="text-center text-success">@TempData["error"]</h1>
            <form method="post">
                <div class="form-group">
                    <label asp-for="Name"></label>
                    <input type="text" asp-for="Name" id="Name" class="form-control" />
                    <span class="text-danger" id="Nameerr"></span>
                </div>
                <div class="form-group">
                    <label asp-for="State"></label>
                    <select class="form-control state" id="State" asp-for="State">
                        <option value="">--Select State--</option>
                    </select>
                    <span class="text-danger" id="Stateerr"></span>
                </div>
                <div class="form-group">
                    <label asp-for="City"></label>
                    <select class="form-control city" id="City" asp-for="City">
                        <option value="">--Select City--</option>
                    </select>
                    <span class="text-danger" id="Cityerr"></span>
                </div>

                <div class="form-group">
                    <input type="submit" id="Submit" class="btn btn-sm btn-info" value="Submit" />
                </div>
            </form>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/JavaScript.js"></script>
<script src="~/js/Custom.js"></script>
<script>
    $(document).ready(function () {
        LoadState()
        $(".state").change(function () {
            var id = $(this).val();
            $(".city").empty();
            $(".city").append("");

            $.get('@Url.Action("GetCity", "Drop")', { "id": id }, function (result) {
                console.log(result)
                $.each(result, function (i, data) {

                    $(".city").append("<option value=" + data.id + ">" + data.name + "</option>")
                });
            });
        });
    });
    function LoadState() {
        $.get('@Url.Action("GetState","Drop")', function (result) {
            $.each(result, function (i, data) {
                $(".state").append("<option value=" + data.id + ">" + data.name + "</option>")
            });
        });
    }
    //function add() {
    //    name = $("#name").val();
    //    state = $("#state").data.name();
    //    city = $("#city").data.name();
    //    $.ajax({
    //        type: "post",
    //        url: "/drop/create/",
    //        data: {
    //            "name": name,
    //            "state": state,
    //            "city": city,
    //        },
    //        success: function (response) {
    //            alert("data saved");
    //        }
    //    })
    //}

</script>

Views/Drop/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-4 offset-4">
        <div class="form-group">
            <label>Select State</label>
            <select class="form-control state">
                <option>Select</option>
            </select>
        </div>

        <div class="form-group">
            <label>Select City</label>
            <select class="form-control city">
                <option>Select</option>
            </select>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/JavaScript.js"></script>
<script>
    $(document).ready(function () {
        LoadState()
        $(".state").change(function () {
            var id = $(this).val();
            $(".city").empty();
            $(".city").append("<option>Select</option>")

            $.get('@Url.Action("GetCity", "Drop")', { "id": id }, function (result) {
                debugger;
                console.log(result)
                $.each(result, function (i, data) {

                    $(".city").append("<option value=" + data.id + ">" + data.name + "</option>")
                });
                debugger;
            });
        });
    });
    function LoadState() {
        $.get('@Url.Action("GetState","Drop")', function (result) {
            $.each(result, function (i, data) {
                $(".state").append("<option value=" + data.id + ">" + data.name + "</option>")
            });
        });
    }
</script>

Views/Dropdown/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

</div>
<div class="row">
    <div class="col-4 offset-4">
        <div class="form-group">
            <label>Select country</label>
            <select class="form-control country">
                <option>Select</option>
            </select>
        </div>

        <div class="form-group">
            <label>Select State</label>
            <select class="form-control state">
                <option>Select</option>
            </select>
        </div>

        <div class="form-group">
            <label>Select City</label>
            <select class="form-control city">
                <option>Select</option>
            </select>
        </div>
    </div>
</div>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery/dist/JavaScript.js"></script>
<script>
    $(document).ready(function () {
        loadCountries()
        //GetCountry()

        $(".country").change(function () {
            var id = $(this).val();
            $(".state").empty();
            $(".state").append("<option>Select</option>")

            $.get('@Url.Action("GetStates", "Dropdown")', { "id": id }, function (result) {
                debugger;
                console.log(result)
                $.each(result, function (i, data) {

                    $(".state").append("<option value=" + data.id + ">" + data.name + "</option>")
                });
                debugger;
            });
        });


        $(".state").change(function () {
            var id = $(this).val();
            $(".city").empty();
            $(".city").append("<option>Select</option>")
            $.get('@Url.Action("GetCities", "Dropdown")', { "id": id }, function (result) {
                console.log(result)
                $.each(result, function (i, data) {

                    $(".city").append("<option value=" + data.id + ">" + data.name + "</option>")
                });
            });
        });
    });
    function loadCountries() {
        $.get('@Url.Action("GetCountries","Dropdown")', function (result) {
            $.each(result, function (i, data) {
                $(".country").append("<option value=" + data.id + ">" + data.name + "</option>") 
            })
        })
    }
    //function GetCountry() {
    //    debugger;
    //    $.ajax({
    //        url: "Dropdown/GetCountries",
    //        type:"GET",
    //        cache: false,
    //        success: function (i, data) {
    //            debugger;
    //            $(".country").append("<option value=" + i.id + ">" + i.name + "</option>")
    //        }
    //    });
    //}

</script>

Views/Dropdown/Validation.cshtml
@{
    ViewData["Title"] = "Validation";
}

<script src="~/js/Custom.js"></script>
<script type="text/javascript">

    function validate() {
        var name = document.f1.name.value;
        var passwordlength = document.f1.password.value.length;
        var status = false;
        if (name == "") {
            document.getElementById("namelocation").innerHTML = "Please enter your name";  
            status = false;
        } else {
            document.getElementById("namelocation").innerHTML = "";
            status = true;
        }
    }
</script>


<form name="f1">
    <table>
        <tr>
            <td>Name:</td>
            <td>
                <input type="text" name="name" />
                <span id="namelocation" style="color:red"></span>
            </td>
        </tr>
    </table>
    <input type="submit" onsubmit="validate()" class="btn btn-sm btn-primary"/>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CascadingDropdown</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CascadingDropdown</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CascadingDropdown - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>